language: node_js
node_js:
  - '8'
env:
  global:
    secure: "JXrw1lwn6g6AQ50l5UOhKOZR4KSWu0iKPmgFsq4Hx+QPEc+wyNVrH4l7MMBA1JldC3emJYNcsrd/Tjsxpm4dJM/XUY/lLFy8bSMPE9BJIUMm8//zMs20k30Bwd/30K5LVwiUIVc+PimsWpKDPsBYH5fNeHBOKPyzifvxlQBXxverMpxSKN7qX/ZpCa/eU6uJ8xCYTOmIyUBuoG1Fl30nXOxMvdA9RViHDTs7MbpP6v4R6UwXMd0rqC8auck7P4kFTsn/prZ//BlLpR7ODj2qKSClNPiXzROv8HzlvepMvedlXDoL7HGCzVCm2wbfMorzD9A4jEeOKB7CXy61RypJ9zVD7WzHsGW4TK18/NfLUf9AjvzViomqPXKZdbJO05OP8yPLt5OuRcObiQaMJM1r0Gr5lOerpNzD6/z1gR41fEyj+KeJb8DA/M85E3UrjixbZXqwfMfznBNziBN3UQrZmZMPyGUzF9AIFPCe9TmEBhPm5NnA6nLeccSwOHjQLAk3dz+Ipre0/vPU/P3LAeFUqehmeSQP08BOX5C/d14jzkHB5MEuavrHBaD930VtDFeqyPJDgLFOW4c60XH3bQ928DSwExULdJpZpiyTRIKVqUKfyGm4bdz0YYW++rdBs31WyYcO0u925V2xn5bOeXAtT+gn+l3cpF7wJInRV4mpTFk="

dist: trusty
sudo: false

addons:
  chrome: stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - bash travis/commit.sh
